### ISSUE TITLE
Blocking read() call in tmnet_packet.cc

### ISSUE THREAD

**Issue by alexonea** [thetopor/topor-media-server#1]
The `tmnet_packet` class provides two methods (`read_header` and `read_payload`) which rely on `read` to fill in the respective fields of the packet. Two issues arise from this:

1. the `read` call is blocking and, when not enough bytes are available, will report a incomplete message (return `E_BADMSG`)
2. when the above scenario happens, all subsequent reads will report `E_BADMSG` and the whole system just fails.

A possible solution is to keep track of the number of bytes read and consider the header completed only when the number of bytes read accumulated to the total header length. Same for payload.

**Comment by OriginalNexus** [comment]
I encountered a similar problem when reading from a stream. I implemented
two functions: wait_read() and wait_skip() to solve my issues. Please see
formats/wav.cc from libtmplay for their implementation and usage.
Maybe a similar approach will solve your problems.

**Comment by alexonea** [comment]
@OriginalNexus I checked your solution and it is not suitable for use in my scenario.

The `read_header` and `read_payload` methods are called from within a `select` loop. Using your `wait_read` function in a select loop means that you block the loop until all bytes are available - which is exactly what you try to avoid with `select`.

Are you also using your `wait_read` function in a select loop?

**Comment by alexonea** [comment]
Closing the issue due to abandoned code.
